{% set name = "ggCaller" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/samhorsfield96/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 3ca39bbab9192d6be8db9d9730e417ad2b6c9bccd44786f4563e06a9a153c639

build:
  number: 0
  skip: True  # [osx]
  script: {{ PYTHON }} setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - ggcaller = ggCaller.__main__:main

requirements:
  build:
    - {{ compiler('c')}}
    - {{ compiler('cxx') }}
    - cmake >=3.4
    - setuptools
    - python >=3
  host:
    - python >=3
    - pybind11
    - llvm-openmp  # [osx]
    - libgomp      # [linux64]
    - seqan3
    - bifrost
    - pthread-stubs
    - zlib
    - bzip2
  run:
    - python >=3
    - bifrost
    - pthread-stubs
    - biopython
    - graph-tool
    - pytorch
    - tqdm
    # The xorg-* requirements are only used for gtk3 which is pulled in via graph-tool.
    - xorg-libxi
    - xorg-libxcursor
    - xorg-libxdamage
    - xorg-libxcomposite
    - xorg-libxrandr
    - xorg-libxinerama
    - xorg-libxpm
    - xorg-libxaw
    - xorg-libxfixes

test:
  imports:
    - ggCaller_cpp
    - balrog
    - ggCaller
  commands:
    - ggcaller -h | grep -q "Generates ORFs from a Bifrost graph."

about:
   home: https://github.com/samhorsfield96/ggCaller
   license: MIT
   license_file: LICENSE
   summary: 'a gene caller for Bifrost graphs'
