{% set name = "inStrain" %}
{% set version = "1.4.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 9c959e908bef03dc4aafb1a719a9271fb4f9a5d020a48e7cfa9c96245ff5acc0

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv --no-deps"

requirements:
  host:
    - pip
    - python >=3.4
  run:
    - biopython <=1.74
    - drep
    - h5py
    - matplotlib-base
    - networkx
    - numpy
    - pandas >=0.25,!=1.1.3
    - psutil
    - pysam
    - pytest
    - python >=3.4
    - scikit-learn
    - seaborn
    - tqdm
    - numba
    - lmfit
    - samtools

test:
  imports:
    - inStrain
  commands:
    - inStrain profile --help
    - inStrain compare --help

about:
  home: "https://github.com/MrOlm/inStrain"
  license: MIT
  license_family: MIT
  summary: "Calculation of strain-level metrics"
