{% set name = "arboreto" %}
{% set version = "0.1.6" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "32fdac5e8a3e0ef2e196b5827f067d815ac4e689d2fca0dc437f42abdeeb89ab" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
 
requirements:
  host:
    - python
    - pip
  run:
    - python
    - scikit-learn
    - numpy
    - scipy
    - pandas
    - dask
    - distributed

test:
  imports:
    - arboreto
    - tests

about:
  home: https://github.com/tmoerman/arboreto
  license: BSD 3-Clause License
  license_family: BSD
  summary: Scalable gene regulatory network inference using tree-based ensemble regressors

