{% set name = "ultraplex" %}
{% set version = "1.0.4.12" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 284db09d1780bc65671ff53758eab7ae686e1dc8db07ce5ec7b3570d10331b01

build:
  noarch: python
  number: 0
  entry_points:
    - ultraplex = ultraplex.__main__:main
  script: "{{ PYTHON }} -m pip install . -vv --ignore-installed --no-deps"

requirements:
  host:
    - pip
    - python
  run:
    - cutadapt ==2.10
    - python

test:
  imports:
    - ultraplex
  commands:
    - ultraplex --help

about:
  home: "https://github.com/ulelab/ultraplex.git"
  license: MIT
  license_family: MIT
  summary: "fastq demultiplexer"

extra:
  recipe-maintainers:
    - Delayed-Gitification
