{% set name = "jcvi" %}
{% set version = "1.1.7" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2709f0e2420da0f9d5a5da581f8f19bd54d7bb9a9720f0d0e9141f30e84b5ab2

build:
  skip: True  # [py2k]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy 
    - cython
  run:
    - python
    - biopython
    - boto3
    - coveralls
    - deap
    - ete3
    - gffutils
    - goatools
    - graphviz
    - jinja2
    - matplotlib-base
    - networkx
    - numpy
    - pypdf2
    - pytest
    - pytest-benchmark
    - pytest-cov
    - pyyaml
    - scipy
    - seaborn

test:
  imports:
    - jcvi
    - jcvi.algorithms
    - jcvi.annotation
    - jcvi.apps
    - jcvi.assembly
    - jcvi.compara
    - jcvi.formats
    - jcvi.graphics
    - jcvi.projects
    - jcvi.utils
    - jcvi.utils.data
    - jcvi.variation

about:
  home: http://github.com/tanghaibao/jcvi
  license: BSD-2-Clause
  license_family: BSD
  summary: Python utility libraries on genome assembly, annotation and comparative genomics
  description: "JCVI utility libraries"
